### PR TITLE
Allow for relative paths in abbr

### PR DESCRIPTION
**Pull request by somini**
This introduces a new setting to `fnamemodify` file locations for
display.

Defaults to the old behaviour of not touching the paths.

This "fixes" my problem with #42

### CODE REVIEW

**Comment by Shougo** [comment]
relative path feature is already implemented though...

**Comment by somini** [comment]
As #42, only for the `word`, and not for the `abbr`, the text string that is shown in the interface.

**Comment by Shougo** [comment]
https://github.com/Shougo/neomru.vim/commit/cf6dd6d02e7a9b61612509a9879c1778364ad5a5

**Comment by somini** [comment]
The only "problem" is that includes many "../../" if the file is not in a subfolder of the current one.

If it is configurable, maybe people will not complain that the format is not to their liking. :-)

**Comment by Shougo** [comment]
Hm...
Please fix the conflict.

**Comment by somini** [comment]
Force pushed.

**Comment by somini** [comment]
Forced pushed the correct version.

That should teach me not to force push while sleepy.

**Comment by Shougo** [comment]
> The only "problem" is that includes many "../../" if the file is not in a subfolder of the current one.

I have fixed the problem.
Please test the latest version.

**Comment by somini** [comment]
I'm assuming this is the commit: https://github.com/Shougo/neomru.vim/commit/51fbd9c6924f8773aa3eb0103faad322fef4504e
It seems you forgot to commit the `denite.util.relpath` function, this broke the plugin.

Note that this approach might be slow, since you are taking every absolute path, modifying it on the Python function and then `expand`ing it in vimscript.

**Comment by Shougo** [comment]
@somini Have you updated denite.nvim?

**Comment by somini** [comment]
Thanks for the tip, I did that.

This new version *still* doesn't solve the issue. Using `:.:~` will force the paths to be relative to the home for projects inside the home directory.

Plus, I introduced a source variable to control the "relativeness" of the path. I use this because I have an alias that shows me only the MRU for the current project, with a relative path to the CWD, and a general source that shows me files relative to the home directory:
```vim
call denite#custom#var('file_mru', 'relative_path', 1) "Relative to ~
call denite#custom#alias('source', 'project/file_mru', 'file_mru')
call denite#custom#var('project/file_mru', 'relative_path', 2) "Relative to .
```
I could probably improve that by specifying directly the `fnamemodify` parameter instead of the current hack.

---

Sorry for the constant back-and-forth, I almost feel bad for keep this alive for so long. I can maintain my custom fork for this small feature, if you have any objections to this PR simply close it, no hard feelings.

**Comment by somini** [comment]
> I could probably improve that by specifying directly the fnamemodify parameter instead of the current hack.

Implemented this.

**Comment by Shougo** [comment]
Please fix the conflict.
I cannot merge it.

**Comment by somini** [comment]
Squashed all commits and force pushed.

**Comment by Shougo** [comment]
Merged.

**Comment by somini** [comment]
Thanks, once again sorry for the constant back and forth.

**Pull request merged**
